//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeCreator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeEntities : DbContext
    {
        public ResumeEntities()
            : base("name=ResumeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CharacterReference> CharacterReferences { get; set; }
        public virtual DbSet<PostGraduate> PostGraduates { get; set; }
        public virtual DbSet<Primary> Primaries { get; set; }
        public virtual DbSet<Secondary> Secondaries { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Strength> Strengths { get; set; }
        public virtual DbSet<Tertiary> Tertiaries { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkExperience> WorkExperiences { get; set; }
    }
}
