//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Period { get; set; }
        public string Position { get; set; }
        public string MainRole { get; set; }
    
        public virtual User User { get; set; }
    }
}
